name: MassiveStyleChat
version: 1.0
main: com.seuprojeto.massivechat.MassiveChatPlugin
api-version: 1.20
author: SeuNome
description: Chat profissional estilo MassiveChat com Markdown e Canais.

commands:
  chat:
    description: Comando principal do chat.
    usage: /chat <reload> ou use os atalhos /g, /l, /rp
    aliases: [g, l, rp]

permissions:
  massivechat.admin:
    description: Permite usar o /chat reload
    default: op
  massivechat.color:
    description: Permite usar cores no chat
    default: true